version: '3.4'

services:
  orgsource:
    image: orgsource
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/usr/src/app
      - usr/src/app/nodes_moduels
    environment:
      NODE_ENV: production
    ports:
      - 4100:4100
