version: "3.7"

services:
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  backend:
    image: backend
    restart: always
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    environment:
      NODE_ENV: production
      NX_POSTGRES_HOST: db
      NX_PORT: 4100
    depends_on:
      - db

    ports:
      - 4100:4100
    develop:
      watch:
      - action: sync
        path: ./frontend
        target: /usr/src/app/backend
      - action: rebuild
        path: package.json
  frontend:
    image: frontend
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    restart: always
    depends_on:
      - backend
    environment:
      NODE_ENV: production
      NX_PORT: 4100
    ports:
      - 4200:4200
    develop:
      watch:
      - action: sync
        path: ./frontend
        target: /usr/src/app/frontend
      - action: rebuild
        path: package.json


