services:
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  backend:
    image: backend
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    environment:
      NODE_ENV: production
      NX_POSTGRES_HOST: db
      NX_PORT: 4100
    depends_on:
      - db

    ports:
      - 4100:4100
  frontend:
    image: frontend
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    depends_on:
      - backend
    environment:
      NODE_ENV: production
      NX_PORT: 4100
      NX_BACKEND_HOST: backend
    ports:
      - 4200:4200
